Add common default MIDI controllers
amsynth/amsynth pull request #225
Opened 2023-04-15 16:49 UTC by gwilherm

Added the following MIDI CC as default mapping:
```
MIDI CC 5  :  kAmsynthParameter_PortamentoTime
MIDI CC 71 :  kAmsynthParameter_FilterResonance
MIDI CC 72 :  kAmsynthParameter_AmpEnvRelease
MIDI CC 73 :  kAmsynthParameter_AmpEnvAttack
MIDI CC 74 :  kAmsynthParameter_FilterCutoff
MIDI CC 91 :  kAmsynthParameter_ReverbWet
```

2023-04-17 10:02 UTC, nickdowell requested changes
Thank you for this contribution!

I agree it's a sensible use of the standard MIDI CCs, just a few minor suggested changes from me.

2023-04-17 20:35 UTC, gwilherm commented on src/core/midi.h
> +    MIDI_CC_REVERB_LEVEL                = 0x5B,
You're right

2023-04-17 20:48 UTC, gwilherm commented on src/core/synth/MidiController.cpp
> +			/* Handled by controller map */
No they are not necessary of course, I've been maybe kinda influenced by the presence of `MIDI_CC_MODULATION_WHEEL_MSB` case

2023-04-18 07:08 UTC, nickdowell commented on src/core/synth/MidiController.cpp
> +			/* Handled by controller map */
Actually these lines might help to silence any compiler / lint warnings about unhandled cases 🙃 let's keep them

2023-04-18 07:09 UTC, nickdowell approved these changes

2023-04-18 07:10 UTC, merged

2023-04-18 19:45 UTC, gwilherm commented
Thanks for the merge and for your awesome work !